development:
  adapter: postgresql
  database: creditcard_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: creditcard_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: creditcard_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
